<?php
	class Messaging {
		
		var $Uids = array();
		var $Title = false;
		var $Subject = false;
		var $Msg_status = false;
		var $Content = false;
		var $Link = false;
		var $Importance = 1; //1 - low, 2 - moderate, 3 - high, 4 - critical
		var $Send_to_email = false;
		
		function Display( ) {
			echo $this->DisplayTitle( );
			echo $this->DisplaySubject( );
			echo $this->Content;
		}
		
		function DisplayTitle( ) {
			if($this->Link) {
				return '<span class="title"><a href="'.WEBSITE_LOC.$this->Link.'">'.$this->Title.'</a></span>';
			} else {
				return '<span class="title">'.$this->Title.'</span>';
			}
		}
		
		
		function DisplaySubject( ) {
				return '<span class="subject">'.$this->Subject.'</span>';
		}
		
		function SetBodyTxt( $Data ) {
			$this->Content = $Data;
		}
	}
	

 $Msg = new Messaging;

 $Content = "<P>This page was generated by the Page Class example.</P>";

 $Msg->Title = "Using Classes in PHP";
 $Msg->Subject = "This is the subject";
 $Msg->SetBodyTxt( $Content );

 $Msg->Display( );

?>